version: '3.8'

services:
  # Base de Datos
  db:
    image: postgres:15-alpine
    container_name: sentimind-db
    restart: always
    environment:
      POSTGRES_DB: sentimind_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Microservicio de Python (IA)
  # Asegúrate de tener el código de Python en una carpeta llamada 'python-service' al mismo nivel
  ai-service:
    build: ../ds # Ruta a donde está el Dockerfile de Python
    container_name: sentimind-ai
    restart: always
    ports:
      - "8000:8000"

  # Backend + Frontend
  app:
    build: .
    container_name: sentimind-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=sentimind_db
      - DB_USERNAME=user_admin
      - DB_PASSWORD=password123
      - AI_INTEGRATION_ENABLED=true
      - AI_API_URL=http://ai-service:8000/predict
    depends_on:
      - db
      - ai-service

volumes:
  postgres_data: